// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeELpMFO8Am2Dp40ELHcPj64NxEq-xpNE',
    appId: '1:217523937201:web:68f1f136fe5d68adf86790',
    messagingSenderId: '217523937201',
    projectId: 'pushnotification-ec487',
    authDomain: 'pushnotification-ec487.firebaseapp.com',
    storageBucket: 'pushnotification-ec487.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBvzVXmdGO2ApzPxNNoyfys6ltKXfCz9Q',
    appId: '1:217523937201:android:6b6e40db112f0d98f86790',
    messagingSenderId: '217523937201',
    projectId: 'pushnotification-ec487',
    storageBucket: 'pushnotification-ec487.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg_2SXd6ups1lapTgMBa1Yw1QlNWh9ca0',
    appId: '1:217523937201:ios:f9e0ea86998705fdf86790',
    messagingSenderId: '217523937201',
    projectId: 'pushnotification-ec487',
    storageBucket: 'pushnotification-ec487.appspot.com',
    iosBundleId: 'com.example.flutterPushnotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg_2SXd6ups1lapTgMBa1Yw1QlNWh9ca0',
    appId: '1:217523937201:ios:63f292a10cb79734f86790',
    messagingSenderId: '217523937201',
    projectId: 'pushnotification-ec487',
    storageBucket: 'pushnotification-ec487.appspot.com',
    iosBundleId: 'com.example.flutterPushnotification.RunnerTests',
  );
}
